### ISSUE TITLE
Rename GuildEmoji to Emoji

### ISSUE THREAD

**Issue by n1c00o** [discordmeow/meow#10]
Because it's "Emoji" in the Discord API and the object can represent a custom emoji or a basic emoji

**Comment by Cat66000** [comment]
Well, I think we should make a different class named Emoji or BaseEmoji, and keep GuildEmoji for guild emojis aka custom emoji

**Comment by n1c00o** [comment]
I think not because it will just add another class. In fact we can just use the sent object because it is typed

**Comment by n1c00o** [comment]
Emoji sounds better than GuildEmoji and if we want to respect the API we should use Emoji and not GuildEmoji

**Comment by Cat66000** [comment]
A basic emoji have less properties than a custom one
I think it would be better and very easy to have classes for basic and custom ones
